### ISSUE TITLE
We should post status updates using the github status api

### ISSUE THREAD

**Issue by franziskuskiefer** [taskcluster/taskcluster-github#46]
(This is @jhford)  We should be posting to the status api that github exposes on conclusion of the task graph with overall status.

**Comment by franziskuskiefer** [comment]
nvm, it looks like we do? https://github.com/taskcluster/taskcluster-github/blob/da7ed2b3552a5010b819e81fd945df4f2f13b953/src/github.js#L32

**Comment by imbstack** [comment]
Yeah, we do that. You can see it if you open the "view details" section at the bottom of [this recent PR](https://github.com/taskcluster/taskcluster-github/pull/44). However, since we do this now, I'd also like to make it stop commenting in the stream that it has started running. Does that sound reasonable to you?
